#!/bin/sh

if [ $(uname) = "Linux" ]; then
    pathCmd="readlink -f"
elif [ $(uname) = "Darwin" ]; then
    pathCmd="stat -f %N"
else
    pathCmd="realpath"
fi

BASEDIR=`dirname $($pathCmd $0)`
TARGET=`echo $BASEDIR/target/scala-*/uppsat-assembly*.jar`
JAVA=java

export JAVA_OPTS="-Xss20000k -Xmx1500m"

exec $JAVA -jar $TARGET "$@"
